#!/bin/bash

is_text_file()
{
    file $1 | grep -q '\<text\>'
}

if [[ $# -lt 1 ]]; then
    echo "usage: difftool [-s] <file1> <file2>"
    echo "    Launch vimdiff on two files only if they differ by more than"
    echo "    header fields which are known to always differ."
    echo "    The -s option will suppress launch of vimdiff and simply print"
    echo "    whether the files differ."
    exit 1
fi

rv=0

# don't diff files if summary desired
summary=
if [ "$1" == "-s" ]; then
    summary=true
    shift
fi

# check existence of files
if [ ! -f "$1" ]; then
    echo "new file: $2"
    exit
fi
if [ ! -f "$2" ]; then
    echo "new file: $1"
    exit
fi

# find vim to use
if which nvim > /dev/null; then
    VIM=nvim
else
    VIM=vim
fi

# only filter text files
if is_text_file "$1" && is_text_file "$2"; then
    # temporary files
    tmp1=/tmp/`basename "$1"`.dodiff1
    tmp2=/tmp/`basename "$2"`.dodiff2

    # filter out header fields which always change
    grep -v '$Header:\|$DateTime:\|$Author:\|$Change:\|$Id:\|$Date:\|Copyright' "$1" > "$tmp1"
    grep -v '$Header:\|$DateTime:\|$Author:\|$Change:\|$Id:\|$Date:\|Copyright' "$2" > "$tmp2"

    f1="$tmp1"
    f2="$tmp2"
else
    f1="$1"
    f2="$2"
fi

# if diff detects changes, launch vimdiff
if ! diff "$f1" "$f2" >/dev/null; then
    if [ $summary ]; then
        echo "files differ: $1 $2"
    else
        echo "==> diff $1 $2"
        $VIM -d -f "$1" "$2"
        rv=$?
    fi
fi

# clean up tmp files
[ -f "$tmp1" ] && rm "$tmp1"
[ -f "$tmp2" ] && rm "$tmp2"

exit $rv

