#!/bin/bash

usage()
{
    echo "usage: difftree [-s] [-a] <directory>"
    echo
    echo "    Recursively find text files in the current directory and diff them"
    echo "    with the corresponding file in a directory with congruent structure."
    echo
    echo "    OPTIONS"
    echo "      -s  Print a summary without launching diff on files"
    echo "      -a  Diff all files, not just text files"
    echo
    exit 1
}

[[ $# -lt 1 ]] && usage

summary=
all=false
while [ $# -gt 1 ]; do
    case $1 in
        -s)
            summary=$1
            shift
            ;;
        -a)
            all=true
            shift
            ;;
        *)
            usage
            ;;
    esac
done
compDir=$1

if $all; then
    files=`find . -path './.git' -prune -o -type f`
else
    #files=`find . -type f ! -iname '*.d' -exec file {} \; | grep '\<text\>' | cut -d':' -f1`
    files=`find . -path './.git' -prune -o -path './build' -prune -o -type f -exec file {} \; | \
                    grep '\<text\>' | cut -d':' -f1`
fi

OIFS="$IFS"
IFS=$'\n'
for file in $files; do
    difftool $summary "$compDir/$file" "$file"
    if [ $? -ne 0 ]; then
        echo "diff canceled"
        break
    fi
done
IFS="$OIFS"

